#+TITLE: Doom Emacs Config
#+PROPERTY: header-args :tangle config.el
* Table of Contents :toc:
- [[#about-this-config][About this config]]
- [[#personal-info][Personal Info]]
  - [[#name-and-email][Name and email]]
  - [[#projects-locations][Projects locations]]
  - [[#org-files-location][Org files location]]
- [[#personal-preferences][Personal preferences]]
  - [[#splash-image][Splash image]]
  - [[#footer][Footer]]
  - [[#theme][Theme]]
  - [[#fonts][Fonts]]
  - [[#comments][Comments]]
  - [[#popup-text][Popup text]]
  - [[#modeline][Modeline]]
  - [[#beacon-mode][Beacon mode]]
  - [[#minimap][Minimap]]
  - [[#line-numbers][Line numbers]]
  - [[#starting-window-dimension][Starting window dimension]]
  - [[#transparency][Transparency]]
  - [[#window-decorators][Window decorators]]
  - [[#warnings-level][Warnings level]]
  - [[#terminals][Terminals]]
  - [[#google-translator][Google translator]]
- [[#programming][Programming]]
  - [[#javascript][Javascript]]
  - [[#ruby][Ruby]]
- [[#version-control-systems][Version control systems]]
  - [[#git][Git]]
- [[#editing-configuration][Editing configuration]]
  - [[#evil][Evil]]
  - [[#completions][Completions]]
  - [[#corfu][Corfu]]
  - [[#lsp-mode][LSP mode]]
  - [[#eglot][Eglot]]
  - [[#rustic][Rustic]]
  - [[#solargraph-or-sorbet][Solargraph or Sorbet]]
  - [[#dired][Dired]]
  - [[#key-chords][Key chords]]
  - [[#harpoon][Harpoon]]
  - [[#search][Search]]
  - [[#indentation][Indentation]]
- [[#containerization][Containerization]]
  - [[#docker][Docker]]
- [[#org][Org]]
  - [[#preferences][Preferences]]
  - [[#svg-tag-mode][Svg-Tag-Mode]]
  - [[#org-modern][Org-modern]]
  - [[#org-appear][Org-appear]]
  - [[#org-roam][Org-Roam]]
  - [[#toc-org][TOC Org]]
- [[#ai][AI]]
  - [[#gptel][GPtel]]

* About this config
This configuration works with Emacs 29.1, you'll need to install Doom Emacs, and Doom Emacs on Rails.

* Personal Info
** Name and email
Set your name and email
#+begin_src emacs-lisp
(setq user-full-name "Alan Maciel"
      user-mail-address "alan.maciel.salcedo@gmail.com")
#+end_src

** Projects locations
MOST IMPORTANT CONFIG - Set your project folders
#+begin_src emacs-lisp
(setq projectile-project-search-path '("~/Projects" "~/Labs"))
#+end_src

** Org files location
If you use `org' and don't want your org files in the default location below, change `org-directory'. It must be set before org loads!
#+begin_src emacs-lisp
(after! org
  (setq org-directory "~/org/")
  (setq org-agenda-files '("~/org/agenda.org"))
  (setq org-log-done 'time )
  (setq org-log-done 'note )
  )
#+end_src

* Personal preferences
** Splash image
Set splash image
#+begin_src emacs-lisp
;; (setq fancy-splash-image "~/dotfiles-local/emacs/doom.d/splash/lucky-doom-emacs-color.png")
#+end_src

Remove splash image
#+begin_src emacs-lisp
(remove-hook '+doom-dashboard-functions #'doom-dashboard-widget-banner)
#+end_src

** Footer
Remove footer
#+begin_src emacs-lisp
(remove-hook '+doom-dashboard-functions #'doom-dashboard-widget-footer)
#+end_src
** Theme
Select the colors you like
#+begin_src emacs-lisp
;; (setq doom-theme 'doom-monokai-octagon
;;       doom-themes-treemacs-enable-variable-pitch nil)
#+end_src

*** Custom themes
If you want to load a custom theme
#+begin_src emacs-lisp
;; (add-to-list 'custom-theme-load-path "~/.emacs.d/themes/")
;; (load-theme 'twilight t)
;; (setq doom-theme 'twilight)
#+end_src

*** Circadian themes
Change themes depending the time of the day
#+begin_src emacs-lisp
;; For day:
;; spacemacs-light, doom-nord-light, doom-gruvbox-light,
;; For night:
;; doom-dracula, doom-gruvbox, doom-sourcerer, doom-spacegray, doom-vibrant
;; doom-oceanic-next, doom-laserwave
;; (defun y/auto-update-theme ()
;;   "depending on time use different theme"
;;   ;; very early => gruvbox-light, solarized-light, nord-light
;;   (let* ((hour (nth 2 (decode-time (current-time))))
;;          (theme (cond ((<= 7 hour 8)   'doom-gruvbox-light)
;;                       ((= 9 hour)      'spacemacs-light)
;;                       ((<= 10 hour 16) 'doom-nord-light)
;;                       ((<= 17 hour 18) 'doom-gruvbox-light)
;;                       ((<= 19 hour 22) 'doom-oceanic-next)
;;                       (t               'doom-laserwave))))
;;     (when (not (equal doom-theme theme))
;;       (setq doom-theme theme)
;;       (load-theme doom-theme t))
;;     ;; run that function again next hour
;;     (run-at-time (format "%02d:%02d" (+ hour 1) 0) nil 'y/auto-update-theme)))
#+end_src

** Fonts
My recommendation is JetBrains Mono. Use M-x reload-user-settings to see the font change
#+begin_src emacs-lisp
(setq doom-font (font-spec :family "CaskaydiaCove Nerd Font Mono" :size 14)
      doom-big-font (font-spec :family "JetBrains Mono" :size 18)
      doom-variable-pitch-font (font-spec :family "Overpass" :size 10)
      doom-serif-font (font-spec :family "IBM Plex Mono" :weight 'light :size 10))
#+end_src

** Comments
I like to see comments in italics
#+begin_src emacs-lisp
(custom-set-faces!
  '(font-lock-comment-face :slant italic))
#+end_src

** Popup text
Automatic documentation popup while autocompleting is nice, but let’s reduce the font size a little bit so that it doesn’t cover the screen too much and makes it easier to skim for information
#+begin_src emacs-lisp
(custom-set-faces! '((corfu-popupinfo) :height 0.9))
#+end_src

** Modeline
#+begin_src emacs-lisp
(use-package! doom-modeline
  :config
  (setq doom-modeline-persp-name t))

(custom-set-faces!
  '(doom-modeline-buffer-modified :foreground "orange"))
#+end_src

*** Height
Some tweaks to doom-modeline
#+begin_src emacs-lisp
(setq doom-modeline-height 30)
#+end_src

*** Hide default encoding
#+begin_src emacs-lisp
(defun doom-modeline-conditional-buffer-encoding ()
  "We expect the encoding to be LF UTF-8, so only show the modeline when this is not the case"
  (setq-local doom-modeline-buffer-encoding
              (unless (and (memq (plist-get (coding-system-plist buffer-file-coding-system) :category)
                                 '(coding-category-undecided coding-category-utf-8))
                           (not (memq (coding-system-eol-type buffer-file-coding-system) '(1 2))))
                t)))

(add-hook 'after-change-major-mode-hook #'doom-modeline-conditional-buffer-encoding)
#+end_src

*** Keycast
#+begin_src emacs-lisp
(use-package! keycast
  :commands keycast-mode
  :config
  (define-minor-mode keycast-mode
    "Show current command and its key binding in the mode line."
    :global t
    (if keycast-mode
        (progn
          (add-hook 'pre-command-hook 'keycast--update t)
          (add-to-list 'global-mode-string '("" mode-line-keycast " ")))
      (remove-hook 'pre-command-hook 'keycast--update)
      (setq global-mode-string (remove '("" mode-line-keycast " ") global-mode-string))))
  (custom-set-faces!
    '(keycast-command :inherit doom-modeline-debug
                      :height 0.9)
    '(keycast-key :inherit custom-modified
                  :height 1.1
                  :weight bold)))
#+end_src

** Beacon mode
Highlight the current line when moving
#+begin_src emacs-lisp
(beacon-mode 1)
#+end_src

** Minimap
If you like this type of things
#+begin_src emacs-lisp
(setq minimap-window-location 'right)
(map! :leader
      (:prefix ("t" . "toggle")
       :desc "Toggle minimap-mode" "M" #'minimap-mode))
#+end_src

** Line numbers
How do you want to display line numbers? t, nil, or relative?
#+begin_src emacs-lisp
;; (setq display-line-numbers-type t)
#+end_src

** Starting window dimension
Start the initial frame not maximized
#+begin_src emacs-lisp
(setq default-frame-alist '((width . 115)(height . 34)))
#+end_src

** Transparency
#+begin_src emacs-lisp
; (add-to-list 'default-frame-alist '(alpha-background . 50))
(add-to-list 'default-frame-alist '(alpha . 95))
#+end_src

** Window decorators
The title bar will have the same color as the window
#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
(add-to-list 'default-frame-alist '(ns-appearance . dark))
#+end_src

Change the window title to something more simple
#+begin_src emacs-lisp
(setq frame-title-format
      '(""
        (:eval
         (if (string-match-p (regexp-quote (or (bound-and-true-p org-roam-directory) "\u0000"))
                             (or buffer-file-name ""))
             (replace-regexp-in-string
              ".*/[0-9]*-?" "☰ "
              (subst-char-in-string ?_ ?\s buffer-file-name))
           "%b"))
        (:eval
         (when-let ((project-name (and (featurep 'projectile) (projectile-project-name))))
           (unless (string= "-" project-name)
             (format (if (buffer-modified-p)  " ◉ %s" "  ●  %s") project-name))))))
#+end_src

** Warnings level
Stop some boring warnings
#+begin_src emacs-lisp
(setq warning-minimum-level :emergency)
#+end_src

** Terminals
Predefined commands:
You can switch to any terminal with SPC l
You can search the commands with SPC o t
You can send any text to any terminal by selecting and pressing SPC l
You can quickly execute a define command with SPC j + the keybinding you defined.

#+begin_src emacs-lisp
(require 'which-key) ;; Needed for which-key to work
(after! which-key
  ;;                         | Name              | command                      | Keybinding |
  (+add-command-to-term-list '("Docker Compose" . "docker-compose up") "u") ;; SPC j u

  ;; Example asking something
  (+add-command-to-term-list '("Add Yarn Package" . (concat "yarn add " (read-string "Package name: "))) "ya") ;; SPC j y a

  ;; Example of dynamic command (using buffer name as example)
  (+add-command-to-term-list '("Rspec on file" . (concat "bundle exec rspec " (buffer-file-name))) "sv") ;; SPC j s v
  (+add-command-to-term-list '("Rspec on line" . (concat "bundle exec rspec " (buffer-file-name) ":" (format "%s" (line-number-at-pos)))) "ss") ;; SPC j s s

  ;; Getting text and executing a command
  (+add-command-to-term-list '("Brownie Test" . (concat "brownie test -k " (save-excursion (search-backward "def test_") (forward-word 2) (thing-at-point 'symbol t)))) "bt") ;; SPC j b t

  ;; Running scripts of a specific folder
  (+add-command-to-term-list '("Brownie Run Script" . (concat "brownie run " (read-file-name "scripts/") " " (read-string "Extra parameters: " nil "commands"))) "br") ;; SPC j b r

  ;; Creating terminal layouts: SPC T
  ;; It will create a new workspace with all terminals listed
  ;;                         | Layout Name    | Commands to execute                |
  (+add-layout-to-term-list '("Rails" . '("rails console" "rails server" nil)))
  (+add-layout-to-term-list '("React" . '("yarn start" nil)))
  (+add-layout-to-term-list '("Next JS" . '("yarn dev" "cowsay 'Have an nice work'" nil)))
  )
#+end_src

#+begin_src emacs-lisp
(setq which-key-idle-delay 0.5) ;; I need the help, I really do

(setq which-key-allow-multiple-replacements t)
(after! which-key
  (pushnew!
   which-key-replacement-alist
   '(("" . "\\`+?evil[-:]?\\(?:a-\\)?\\(.*\\)") . (nil . "◂\\1"))
   '(("\\`g s" . "\\`evilem--?motion-\\(.*\\)") . (nil . "◃\\1"))
   ))
#+end_src

** Google translator
Google Traductor, source and target languages
#+begin_src emacs-lisp
(setq google-translate-default-source-language "en")
(setq google-translate-default-target-language "es-MX")
#+end_src

* Programming
** Javascript
Change Javascript autoformat
#+begin_src emacs-lisp
(setq-hook! 'rjsx-mode-hook +format-with 'prettier)
(setq-hook! 'typescript-tsx-mode-hook +format-with 'prettier)
(setq-hook! 'typescript-mode-hook +format-with 'prettier)
#+end_src

** Ruby
*** Version managers
**** Rbenv
If you use macos with rbenv on homebrew, add it, uncomment it
#+begin_src emacs-lisp
;; (setq rbenv-executable "/usr/local/opt/rbenv/bin/rbenv") ;; Rosetta (intel emulation)
;; (setq rbenv-executable "/opt/homebrew/bin/rbenv") ;; Arm (normal brew)
#+end_src

**** Asdf
ASDF instead of rbenv.
#+begin_src emacs-lisp
;; (add-to-list 'load-path (expand-file-name "~/.config/doom/asdf.el"))
;; (require 'asdf)

;; (asdf-enable) ;; This ensures Emacs has the correct paths to asdf shims and bin
#+end_src

*** Testing
**** Minitest
Do you use minitest instead or rspec
#+begin_src emacs-lisp
(use-minitest "_test")
#+end_src

**** RSpec

*** Rubocop
**** Rubocop on current file
#+begin_src emacs-lisp
(setq rubocop-on-current-file-command "bundle exec rubocop -A ") ;; SPC =
#+end_src

**** Disable rubocop
Disable Rubocop or any other lint if you want.  Linter list on: SPC h v flycheck-checkers
#+begin_src emacs-lisp
;; (add-hook 'ruby-mode-hook
;;  (lambda ()
;;    (setq-local flychech-checker nil)
;;    (setq-local flycheck-disabled-checkers '(ruby-reek lsp ruby-rubylint ruby-rubocop))) 1000)
#+end_src

* Version control systems
** Git
*** Git gutter
The diff changes are reflected in the left fringe. However, I find them to be a little bit too intrusive, so let’s change how they looks by blending the colors into the background a little bit.
#+begin_src emacs-lisp
(use-package! diff-hl
  :config
  (custom-set-faces!
    `((diff-hl-change)
      :foreground ,(doom-blend (doom-color 'bg) (doom-color 'blue) 0.5))
    `((diff-hl-insert)
      :foreground ,(doom-blend (doom-color 'bg) (doom-color 'green) 0.5)))
)
#+end_src

*** Magit
Start projectile with magit, uncomment below:
#+begin_src emacs-lisp
(after! projectile
  (defun open-projectile-with-magit (&optional DIRECTORY CACHE)
    (interactive)
    (magit-status DIRECTORY)
    (if (fboundp 'magit-fetch-from-upstream)
        (call-interactively #'magit-fetch-from-upstream)
      (call-interactively #'magit-fetch-current)))
  (setq +workspaces-switch-project-function #'open-projectile-with-magit))
#+end_src

Build your own file switches here
#+begin_src emacs-lisp
;; (after! projectile-rails
;;   ;; Example: switch from app/contracts/{resource}.rb to app/services/{resource} and vice-versa
;;   (defun projectile-rails-find-contract ()
;;     "Switch from contract to service and vice versa."
;;     (interactive)
;;     (if (string-match-p "app/contracts" (buffer-file-name)) (find-file (replace-regexp-in-string "contract" "service" (replace-regexp-in-string "_contracts" "_services" (buffer-file-name))))
;;       (find-file (replace-regexp-in-string "service" "contract" (replace-regexp-in-string "_services" "_contracts" (buffer-file-name))))))
;;   (map! :leader "rQ" #'projectile-rails-find-contract) ;; Uncomment to bind to SPC r q
;;   )
#+end_src

* Editing configuration
** Evil
#+begin_src emacs-lisp
(use-package! evil-escape
  :config
  (setq evil-esc-delay 0.25))

(use-package! evil-vimish-fold
  :config
  (global-evil-vimish-fold-mode))

(use-package! evil-goggles
  :init
  (setq evil-goggles-enable-change t
        evil-goggles-enable-delete t
        evil-goggles-pulse         t
        evil-goggles-duration      0.25)
  :config
  (custom-set-faces!
    `((evil-goggles-yank-face evil-goggles-surround-face)
      :background ,(doom-blend (doom-color 'blue) (doom-color 'bg-alt) 0.5)
      :extend t)
    `(evil-goggles-paste-face
      :background ,(doom-blend (doom-color 'green) (doom-color 'bg-alt) 0.5)
      :extend t)
    `(evil-goggles-delete-face
      :background ,(doom-blend (doom-color 'red) (doom-color 'bg-alt) 0.5)
      :extend t)
    `(evil-goggles-change-face
      :background ,(doom-blend (doom-color 'orange) (doom-color 'bg-alt) 0.5)
      :extend t)
    `(evil-goggles-commentary-face
      :background ,(doom-blend (doom-color 'grey) (doom-color 'bg-alt) 0.5)
      :extend t)
    `((evil-goggles-indent-face evil-goggles-join-face evil-goggles-shift-face)
      :background ,(doom-blend (doom-color 'yellow) (doom-color 'bg-alt) 0.25)
      :extend t)
    ))
#+end_src

** Completions
*** Orderless
Set orderless matching styles to include char-fold-to-regexp.
#+begin_src emacs-lisp
(use-package! orderless
  :config
  (add-to-list 'orderless-matching-styles 'char-fold-to-regexp))
#+end_src

** Corfu
*** Yasnippet
Suggest yasnippet as completion.
#+begin_src emacs-lisp
;; (use-package! cape-yasnippet
;;   :after (corfu yasnippet)
;;   :init
;;   (add-to-list 'completion-at-point-functions #'cape-yasnippet))
#+end_src

#+begin_src emacs-lisp
;; (use-package! yasnippet
;;   :config
;;   ;; It will test whether it can expand, if yes, change cursor color
;;   (defun hp/change-cursor-color-if-yasnippet-can-fire (&optional field)
;;     (interactive)
;;     (setq yas--condition-cache-timestamp (current-time))
;;     (let (templates-and-pos)
;;       (unless (and yas-expand-only-for-last-commands
;;                    (not (member last-command yas-expand-only-for-last-commands)))
;;         (setq templates-and-pos (if field
;;                                     (save-restriction
;;                                       (narrow-to-region (yas--field-start field)
;;                                                         (yas--field-end field))
;;                                       (yas--templates-for-key-at-point))
;;                                   (yas--templates-for-key-at-point))))
;;       (set-cursor-color (if (and templates-and-pos (first templates-and-pos)
;;                                  (eq evil-state 'insert))
;;                             (doom-color 'red)
;;                           (face-attribute 'default :foreground)))))
;;   :hook (post-command . hp/change-cursor-color-if-yasnippet-can-fire))
#+end_src

** LSP mode
#+begin_src emacs-lisp
(use-package! lsp-ui
  :config
  (setq lsp-ui-doc-delay 2
        lsp-ui-doc-max-width 80)
  (setq lsp-signature-function 'lsp-signature-posframe))
#+end_src

** Eglot
#+begin_src emacs-lisp
(use-package eglot
  :config
  (setq eglot-events-buffer-size 0
        eglot-ignored-server-capabilities '(:inlayHintProvider)
        eglot-confirm-server-initiated-edits nil))
#+end_src

** Rustic
#+begin_src emacs-lisp
(use-package rustic
  :config
  ; Tell rustic where to find the cargo binary
  (setq rustic-cargo-bin-remote "/usr/local/cargo/bin/cargo")
  (setq rustic-lsp-client 'eglot))
#+end_src

** Solargraph or Sorbet
Use sorbet instead solargraph?
#+begin_src emacs-lisp
;; (after! lsp-mode
;;   (setq lsp-disabled-clients '(ruby-ls solargraph))
;;   (setq lsp-sorbet-use-bundler t))
#+end_src

** Dired
#+begin_src emacs-lisp
(map! :leader
      (:prefix ("d" . "dired")
       :desc "Open dired" "d" #'dired
       :desc "Dired jump to current" "j" #'dired-jump)
      (:after dired
       (:map dired-mode-map
        :desc "Peep-dired image previews" "f v" #'peep-dired
        :desc "Dired view file" "f V" #'dired-view-file)))
#+end_src

*** Mode map
#+begin_src emacs-lisp
(evil-define-key 'normal dired-mode-map
  (kbd "M-RET") 'dired-display-file
  (kbd "h") 'dired-up-directory
  (kbd "l") 'dired-open-file ; use dired-find-file instead of dired-open.
  (kbd "m") 'dired-mark
  (kbd "t") 'dired-toggle-marks
  (kbd "u") 'dired-unmark
  (kbd "C") 'dired-do-copy
  (kbd "D") 'dired-do-delete
  (kbd "J") 'dired-goto-file
  (kbd "M") 'dired-do-chmod
  (kbd "O") 'dired-do-chown
  (kbd "P") 'dired-do-print
  (kbd "R") 'dired-do-rename
  (kbd "T") 'dired-do-touch
  (kbd "Y") 'dired-copy-filenamecopy-filename-as-kill ; copies filename to kill ring.
  (kbd "+") 'dired-create-directory
  (kbd "-") 'dired-up-directory
  (kbd "% l") 'dired-downcase
  (kbd "% u") 'dired-upcase
  (kbd "; d") 'epa-dired-do-decrypt
  (kbd "; e") 'epa-dired-do-encrypt)

#+end_src

**** Peep dired
#+begin_src emacs-lisp
(evil-define-key 'normal peep-dired-mode-map
  (kbd "j") 'peep-dired-next-file
  (kbd "k") 'peep-dired-prev-file)
(add-hook 'peep-dired-hook 'evil-normalize-keymaps)
#+end_src

*** Icons in dired
Get file icons in dired
With dired-open plugin, you can launch external programs for certain extensions
For example, I set all .png files to open in 'sxiv' and all .mp4 files to open in 'mpv'
#+begin_src emacs-lisp
(use-package all-the-icons
  :if (display-graphic-p))

;; (add-hook 'dired-mode-hook 'all-the-icons-dired-mode)
;; (setq dired-open-extensions '(("gif" . "sxiv")
;;                               ("jpg" . "sxiv")
;;                               ("png" . "sxiv")
;;                               ("mkv" . "mpv")
;;                               ("mp4" . "mpv")))

;; (use-package dired
;;   :config
;;   (use-package treemacs-icons-dired
;;     :if (display-graphic-p)
;;     :config (treemacs-icons-dired-mode)))

;; (add-hook 'dired-mode-hook 'treemacs-icons-dired-mode)
;; (add-hook 'dired-mode-hook 'all-the-icons-dired-mode)

;; (use-package dired
;;   :config
;;   (use-package all-the-icons-dired
;;     :if (display-graphic-p)
;;     :hook (dired-mode . all-the-icons-dired-mode)
;;     :config (setq all-the-icons-dired nil)))
#+end_src

** Key chords
Using chords fd or jh in the homerow instead of trying to reach esc everytime.
#+begin_src emacs-lisp
(require 'key-chord)
(key-chord-mode t)
(key-chord-define-global "ue" 'evil-normal-state) ;; in DVORAK
(key-chord-define-global "UE" 'evil-normal-state) ;; in DVORAK
(key-chord-define-global "fd" 'evil-normal-state) ;; in QWERTY
(key-chord-define-global "FD" 'evil-normal-state) ;; in QWERTY
#+end_src

** Harpoon
Harpoon separate by branch? (Harpoon leader key: ,)
#+begin_src emacs-lisp
(setq harpoon-separate-by-branch nil)
#+end_src

** Search
*** Ignore folders
#+begin_src emacs-lisp
(after! projectile
  (setq projectile-globally-ignored-directories '("flow-typed" "node_modules" "~/.config/emacs/.local/" ".idea" ".vscode" ".ensime_cache" ".eunit" ".git" ".hg" ".fslckout" "_FOSSIL_" ".bzr" "_darcs" ".tox" ".svn" ".stack-work" ".ccls-cache" ".cache" ".clangd")))
#+end_src

*** Custom searches
Add your custom searches (in rails folders)
#+begin_src emacs-lisp
(after! projectile-rails
  (doom-emacs-on-rails-add-custom-projectile-finder "services" "app/services/"  "\\(.+\\)\\.rb$" "app/services/${filename}.rb" "rt")
  (doom-emacs-on-rails-add-custom-projectile-finder "admin" "app/admin/"  "\\(.+\\)\\.rb$" "app/admin/${filename}.rb" "rt")
  (doom-emacs-on-rails-add-custom-projectile-finder "contracts" "app/contracts/"  "\\(.+\\)\\.rb$" "app/contracts/${filename}.rb" "rq"))
#+end_src

** Indentation
Fix your identation level for stuff?
#+begin_src emacs-lisp
(setq js-indent-level 2)
(setq ts-indent-level 2)
(setq typescript-indent-level 2)
(setq ruby-indent-level 2)
(setq standard-indent 2)
#+end_src

* Containerization
** Docker
*** Config
If you want to use Docker first, configure you docker variables:
#+begin_src emacs-lisp
;; (load (expand-file-name "modules/docker.el" doom-user-dir))

;; (setq ruby-docker-compose-command "docker-compose") ;; You docker-compose command (tip: you can use "cd ../; docker-compose")
;; (setq ruby-docker-rails-server-command "up") ;' To start rails server with SPC r R (docker-compose is implicit)
;; (setq ruby-docker-rails-console-command "run {{container}} rails console") ;; to start rails console (docker-compose is implicit)

;; (setq ruby-docker-rubocop-command "run {{container}} rubocop -a ") ;; Command to run rubocop on current file with SPC =
;; (setq ruby-docker-compose-cwd "/app/")
;; (setq ruby-docker-compose-container "web")
#+end_src

*** Ruby
#+begin_src emacs-lisp
;; Tip here:  You can use M-x rbenv-use and select one version that has solargraph.  You can also install with apt or brew.
;; (setq ruby-docker-disable-solargraph nil) ;; If you want to disable solargraph, change to t.  PS:  You can use solargraph by removing .ruby-version of your project and using from rbenv.
;; (use-ruby-docker)
;;
;; End Docker
#+end_src
* Org
** Preferences
*** Custom faces
#+begin_src emacs-lisp
(after! org
  ;; Set some faces
  (custom-set-faces!
    `((org-quote)
      :foreground ,(doom-color 'blue) :extend t)
    `((org-block-begin-line org-block-end-line)
      :background ,(doom-color 'bg)))
  ;; Change how LaTeX and image previews are shown
  (setq org-highlight-latex-and-related '(native entities script)
        org-image-actual-width (min (/ (display-pixel-width) 3) 800)))
#+end_src

Emacs version 29 can now tell the difference between ‘regular’ or ’normal’ font weights and ‘medium’ weights. Let’s use the medium weights for org-mode headings.

#+begin_src emacs-lisp
(after! org-mode
  (custom-set-faces!
    `((org-document-title)
      :foreground ,(face-attribute 'org-document-title :foreground)
      :height 1.3 :weight bold)
    `((org-level-1)
      :foreground ,(face-attribute 'outline-1 :foreground)
      :height 1.1 :weight medium)
    `((org-level-2)
      :foreground ,(face-attribute 'outline-2 :foreground)
      :weight medium)
    `((org-level-3)
      :foreground ,(face-attribute 'outline-3 :foreground)
      :weight medium)
    `((org-level-4)
      :foreground ,(face-attribute 'outline-4 :foreground)
      :weight medium)
    `((org-level-5)
      :foreground ,(face-attribute 'outline-5 :foreground)
      :weight medium)))
#+end_src

*** Pretty bullets
#+begin_src emacs-lisp
(add-hook 'org-mode-hook 'org-indent-mode)
(use-package org-bullets)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src

*** Current line
Turn off highlighting current line, highlight mode is nice. However, in an Org-mode buffer, I feel like it might be too much. Let’s turn off hl-line-mode in text buffers for now.
#+begin_src emacs-lisp
(add-hook 'text-mode-hook (lambda () (hl-line-mode -1)))
#+end_src

** Svg-Tag-Mode
The configurations for svg-tag-mode go here, too:
#+begin_src emacs-lisp
(use-package! svg-tag-mode
  :config
  (defconst date-re "[0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}")
  (defconst time-re "[0-9]\\{2\\}:[0-9]\\{2\\}")
  (defconst day-re "[A-Za-z]\\{3\\}")
  (defconst day-time-re (format "\\(%s\\)? ?\\(%s\\)?" day-re time-re))

  (defun svg-progress-percent (value)
    (svg-image (svg-lib-concat
                (svg-lib-progress-bar
                 (/ (string-to-number value) 100.0) nil
                 :height 0.8 :foreground (doom-color 'fg) :background (doom-color 'bg)
                 :margin 0 :stroke 2 :radius 3 :padding 2 :width 11)
                (svg-lib-tag (concat value "%") nil
                             :height 0.8 :foreground (doom-color 'fg) :background (doom-color 'bg)
                             :stroke 0 :margin 0)) :ascent 'center))

  (defun svg-progress-count (value)
    (let* ((seq (mapcar #'string-to-number (split-string value "/")))
           (count (float (car seq)))
           (total (float (cadr seq))))
      (svg-image (svg-lib-concat
                  (svg-lib-progress-bar (/ count total) nil
                                        :foreground (doom-color 'fg)
                                        :background (doom-color 'bg) :height 0.8
                                        :margin 0 :stroke 2 :radius 3 :padding 2 :width 11)
                  (svg-lib-tag value nil
                               :foreground (doom-color 'fg)
                               :background (doom-color 'bg)
                               :stroke 0 :margin 0 :height 0.8)) :ascent 'center)))

  (set-face-attribute 'svg-tag-default-face nil :family "Alegreya Sans")
  (setq svg-tag-tags
        `(;; Progress e.g. [63%] or [10/15]
          ("\\(\\[[0-9]\\{1,3\\}%\\]\\)" . ((lambda (tag)
                                            (svg-progress-percent (substring tag 1 -2)))))
          ("\\(\\[[0-9]+/[0-9]+\\]\\)" . ((lambda (tag)
                                            (svg-progress-count (substring tag 1 -1)))))
          ;; Task priority e.g. [#A], [#B], or [#C]
          ("\\[#A\\]" . ((lambda (tag) (svg-tag-make tag :face 'error :inverse t :height .85
                                                     :beg 2 :end -1 :margin 0 :radius 10))))
          ("\\[#B\\]" . ((lambda (tag) (svg-tag-make tag :face 'warning :inverse t :height .85
                                                     :beg 2 :end -1 :margin 0 :radius 10))))
          ("\\[#C\\]" . ((lambda (tag) (svg-tag-make tag :face 'org-todo :inverse t :height .85
                                                     :beg 2 :end -1 :margin 0 :radius 10))))
          ;; Keywords
          ("TODO" . ((lambda (tag) (svg-tag-make tag :inverse t :height .85 :face 'org-todo))))
          ("HOLD" . ((lambda (tag) (svg-tag-make tag :height .85 :face 'org-todo))))
          ("DONE\\|STOP" . ((lambda (tag) (svg-tag-make tag :inverse t :height .85 :face 'org-done))))
          ("NEXT\\|WAIT" . ((lambda (tag) (svg-tag-make tag :inverse t :height .85 :face '+org-todo-active))))
          ("REPEAT\\|EVENT\\|PROJ\\|IDEA" .
           ((lambda (tag) (svg-tag-make tag :inverse t :height .85 :face '+org-todo-project))))
          ("REVIEW" . ((lambda (tag) (svg-tag-make tag :inverse t :height .85 :face '+org-todo-onhold))))))
  :hook (org-mode . svg-tag-mode)
)

(setq svg-tag-tags
      '((":TODO:" . ((lambda (tag) (svg-tag-make "TODO"))))))
(setq svg-tag-tags
      '((":HELLO:" .  ((lambda (tag) (svg-tag-make "HELLO"))
                       (lambda () (interactive) (message "Hello world!"))
                       "Print a greeting message"))))
(setq svg-tag-tags
      '((":TODO:" . ((lambda (tag) (svg-tag-make tag))))))
(setq svg-tag-tags
      '(("\\(:[A-Z]+:\\)" . ((lambda (tag)
                               (svg-tag-make tag :beg 1 :end -1))))))
(setq svg-tag-tags
      '(("\\(:[A-Z]+\\)\|[a-zA-Z#0-9]+:" . ((lambda (tag)
                                           (svg-tag-make tag :beg 1 :inverse t
                                                          :margin 0 :crop-right t))))
        (":[A-Z]+\\(\|[a-zA-Z#0-9]+:\\)" . ((lambda (tag)
                                           (svg-tag-make tag :beg 1 :end -1
                                                         :margin 0 :crop-left t))))))
(setq svg-tag-tags
      '(("\\(:#[A-Za-z0-9]+\\)" . ((lambda (tag)
                                     (svg-tag-make tag :beg 2))))
        ("\\(:#[A-Za-z0-9]+:\\)$" . ((lambda (tag)
                                       (svg-tag-make tag :beg 2 :end -1))))))
#+end_src

*** Fix render in agenda
#+begin_src emacs-lisp
  (defun org-agenda-show-svg ()
    (let* ((case-fold-search nil)
           (keywords (mapcar #'svg-tag--build-keywords svg-tag--active-tags))
           (keyword (car keywords)))
      (while keyword
        (save-excursion
          (while (re-search-forward (nth 0 keyword) nil t)
            (overlay-put (make-overlay
                          (match-beginning 0) (match-end 0))
                         'display  (nth 3 (eval (nth 2 keyword)))) ))
        (pop keywords)
        (setq keyword (car keywords)))))
  (add-hook 'org-agenda-finalize-hook #'org-agenda-show-svg)
#+end_src

** Org-modern
org-modern is really cool – especially when combined with svg-tag-mode. The only downside is it doesn’t play well with org-indent-mode (for now).
#+begin_src emacs-lisp
(use-package! org-modern
  :hook (org-mode . org-modern-mode)
  :config
  (setq
   ;; Edit settings
   org-catch-invisible-edits 'show-and-error
   org-special-ctrl-a/e t
   org-insert-heading-respect-content t
   ;; Appearance
   org-modern-radio-target    '("❰" t "❱")
   org-modern-internal-target '("↪ " t "")
   org-modern-todo nil
   org-modern-tag nil
   org-modern-timestamp t
   org-modern-statistics nil
   org-modern-progress nil
   org-modern-priority nil
   org-modern-horizontal-rule "──────────"
   org-modern-hide-stars "·"
   org-modern-star ["⁖"]
   org-modern-keyword "‣"
   org-modern-list '((43 . "•")
                     (45 . "–")
                     (42 . "↪")))
  (custom-set-faces!
    `((org-modern-tag)
      :background ,(doom-blend (doom-color 'blue) (doom-color 'bg) 0.1)
      :foreground ,(doom-color 'grey))
    `((org-modern-radio-target org-modern-internal-target)
      :inherit 'default :foreground ,(doom-color 'blue)))
  )
#+end_src

** Org-appear
org-appear for seemless look:
#+begin_src emacs-lisp
;; (use-package! org-appear
;;   :hook
;;   (org-mode . org-appear-mode)
;;   :config
;;   (setq org-hide-emphasis-markers t
;;         org-appear-autolinks 'just-brackets))
#+end_src

** Org-Roam
*** Installation
#+begin_src emacs-lisp
(use-package org-roam
  ;; :ensure t
  :custom
  (org-roam-directory (file-truename "~/RoamNotes"))
  :bind (("C-c n l" . org-roam-buffer-toggle)
         ("C-c n f" . org-roam-node-find)
         ("C-c n g" . org-roam-graph)
         ("C-c n i" . org-roam-node-insert)
         ("C-c n c" . org-roam-capture)
         ;; Dailies
         ("C-c n j" . org-roam-dailies-capture-today)
         ("C-M-i" . completion-at-point))
  :config
  ;; If you're using a vertical completion framework, you might want a more informative completion interface
  (setq org-roam-node-display-template (concat "${title:*} " (propertize "${tags:10}" 'face 'org-tag)))
  (org-roam-db-autosync-mode)
  ;; If using org-roam-protocol
  (require 'org-roam-protocol))
#+end_src
*** Files location
#+begin_src emacs-lisp
(setq frame-title-format
      '(""
        (:eval
         (if (s-contains-p (file-truename "~/RoamNotes") (or buffer-file-name ""))
             (replace-regexp-in-string
              ".*/[0-9]*-?" "☰ "
              (subst-char-in-string ?_ ?  buffer-file-name))
           "%b"))
        (:eval
         (let ((project-name (projectile-project-name)))
           (unless (string= "-" project-name)
             (format (if (buffer-modified-p)  " ◉ %s" "  ●  %s") project-name))))))
#+end_src

*** Window title
#+begin_src emacs-lisp
;; (setq frame-title-format
;;       '(""
;;         (:eval
;;          (if (s-contains-p org-roam-directory (or buffer-file-name ""))
;;              (replace-regexp-in-string
;;               ".*/[0-9]*-?" "☰ "
;;               (subst-char-in-string ?_ ?  buffer-file-name))
;;            "%b"))
;;         (:eval
;;          (let ((project-name (projectile-project-name)))
;;            (unless (string= "-" project-name)
;;              (format (if (buffer-modified-p)  " ◉ %s" "  ●  %s") project-name))))))
#+end_src

#+RESULTS:

*** Websocket
#+begin_src emacs-lisp
(use-package! websocket
    :after org-roam)
#+end_src

*** Org-Roam UI
#+begin_src emacs-lisp
(use-package! org-roam-ui
    :after org-roam ;; or :after org
;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
;;         a hookable mode anymore, you're advised to pick something yourself
;;         if you don't care about startup time, use
;; :hook (after-init . org-roam-ui-mode)
    :config
    (setq org-roam-ui-sync-theme t
          org-roam-ui-follow t
          org-roam-ui-update-on-save t
          org-roam-ui-open-on-start t))

(add-to-list 'display-buffer-alist
             '("\\*org-roam\\*"
               (display-buffer-in-side-window)
               (side . right)
               (slot . 0)
               (window-width . 0.33)
               (window-parameters . ((no-other-window . t)
                                     (no-delete-other-windows . t)))))
#+end_src

** TOC Org
#+begin_src emacs-lisp
(if (require 'toc-org nil t)
    (progn
      (add-hook 'org-mode-hook 'toc-org-mode)

      ;; enable in markdown, too
      (add-hook 'markdown-mode-hook 'toc-org-mode)
      (define-key markdown-mode-map (kbd "\C-c\C-o") 'toc-org-markdown-follow-thing-at-point))
  (warn "toc-org not found"))

(use-package toc-org
    :commands toc-org-enable
    :init (add-hook 'org-mode-hook 'toc-org-enable))
#+end_src

* AI
** GPtel
#+begin_src emacs-lisp
(use-package! gptel
  :commands gptel gptel-menu gptel-mode gptel-send gptel-set-tpic
  :config
  (let (ollama-models)
    (when (executable-find "ollama")
      (with-temp-buffer
        (call-process "ollama" nil t nil "list")
        (goto-char (point-min))
        (forward-line 1)
        (while (and (not (eobp)) (looking-at "[^ \t]+"))
          (push (match-string 0) ollama-models)
          (forward-line 1))))
    (setq-default gptel-model "nous-hermes2:latest"
                  gptel-backend (gptel-make-ollama "Ollama" :models ollama-models :stream t)))
  (setq gptel-default-mode #'org-mode))
#+end_src
